// Code generated by ent, DO NOT EDIT.

package hubsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLTE(FieldID, id))
}

// Section applies equality check predicate on the "section" field. It's identical to SectionEQ.
func Section(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldSection, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldRevision, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldUpdateTime, v))
}

// SectionEQ applies the EQ predicate on the "section" field.
func SectionEQ(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldSection, v))
}

// SectionNEQ applies the NEQ predicate on the "section" field.
func SectionNEQ(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNEQ(FieldSection, v))
}

// SectionIn applies the In predicate on the "section" field.
func SectionIn(vs ...string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIn(FieldSection, vs...))
}

// SectionNotIn applies the NotIn predicate on the "section" field.
func SectionNotIn(vs ...string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotIn(FieldSection, vs...))
}

// SectionGT applies the GT predicate on the "section" field.
func SectionGT(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGT(FieldSection, v))
}

// SectionGTE applies the GTE predicate on the "section" field.
func SectionGTE(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGTE(FieldSection, v))
}

// SectionLT applies the LT predicate on the "section" field.
func SectionLT(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLT(FieldSection, v))
}

// SectionLTE applies the LTE predicate on the "section" field.
func SectionLTE(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLTE(FieldSection, v))
}

// SectionContains applies the Contains predicate on the "section" field.
func SectionContains(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldContains(FieldSection, v))
}

// SectionHasPrefix applies the HasPrefix predicate on the "section" field.
func SectionHasPrefix(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldHasPrefix(FieldSection, v))
}

// SectionHasSuffix applies the HasSuffix predicate on the "section" field.
func SectionHasSuffix(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldHasSuffix(FieldSection, v))
}

// SectionEqualFold applies the EqualFold predicate on the "section" field.
func SectionEqualFold(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEqualFold(FieldSection, v))
}

// SectionContainsFold applies the ContainsFold predicate on the "section" field.
func SectionContainsFold(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldContainsFold(FieldSection, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLTE(FieldRevision, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.HubSetting {
	return predicate.HubSetting(sql.FieldLTE(FieldUpdateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HubSetting) predicate.HubSetting {
	return predicate.HubSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HubSetting) predicate.HubSetting {
	return predicate.HubSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HubSetting) predicate.HubSetting {
	return predicate.HubSetting(sql.NotPredicates(p))
}
