// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/hubsetting"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// HubSettingUpdate is the builder for updating HubSetting entities.
type HubSettingUpdate struct {
	config
	hooks    []Hook
	mutation *HubSettingMutation
}

// Where appends a list predicates to the HubSettingUpdate builder.
func (_u *HubSettingUpdate) Where(ps ...predicate.HubSetting) *HubSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSection sets the "section" field.
func (_u *HubSettingUpdate) SetSection(v string) *HubSettingUpdate {
	_u.mutation.SetSection(v)
	return _u
}

// SetNillableSection sets the "section" field if the given value is not nil.
func (_u *HubSettingUpdate) SetNillableSection(v *string) *HubSettingUpdate {
	if v != nil {
		_u.SetSection(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *HubSettingUpdate) SetValue(v json.RawMessage) *HubSettingUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// AppendValue appends value to the "value" field.
func (_u *HubSettingUpdate) AppendValue(v json.RawMessage) *HubSettingUpdate {
	_u.mutation.AppendValue(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *HubSettingUpdate) SetRevision(v int64) *HubSettingUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *HubSettingUpdate) SetNillableRevision(v *int64) *HubSettingUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *HubSettingUpdate) AddRevision(v int64) *HubSettingUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *HubSettingUpdate) SetUpdatedBy(v string) *HubSettingUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *HubSettingUpdate) SetNillableUpdatedBy(v *string) *HubSettingUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *HubSettingUpdate) ClearUpdatedBy() *HubSettingUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *HubSettingUpdate) SetUpdateTime(v time.Time) *HubSettingUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the HubSettingMutation object of the builder.
func (_u *HubSettingUpdate) Mutation() *HubSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HubSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HubSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := hubsetting.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HubSettingUpdate) check() error {
	if v, ok := _u.mutation.Section(); ok {
		if err := hubsetting.SectionValidator(v); err != nil {
			return &ValidationError{Name: "section", err: fmt.Errorf(`ent: validator failed for field "HubSetting.section": %w`, err)}
		}
	}
	return nil
}

func (_u *HubSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hubsetting.Table, hubsetting.Columns, sqlgraph.NewFieldSpec(hubsetting.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Section(); ok {
		_spec.SetField(hubsetting.FieldSection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(hubsetting.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hubsetting.FieldValue, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(hubsetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(hubsetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(hubsetting.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(hubsetting.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(hubsetting.FieldUpdateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HubSettingUpdateOne is the builder for updating a single HubSetting entity.
type HubSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HubSettingMutation
}

// SetSection sets the "section" field.
func (_u *HubSettingUpdateOne) SetSection(v string) *HubSettingUpdateOne {
	_u.mutation.SetSection(v)
	return _u
}

// SetNillableSection sets the "section" field if the given value is not nil.
func (_u *HubSettingUpdateOne) SetNillableSection(v *string) *HubSettingUpdateOne {
	if v != nil {
		_u.SetSection(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *HubSettingUpdateOne) SetValue(v json.RawMessage) *HubSettingUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// AppendValue appends value to the "value" field.
func (_u *HubSettingUpdateOne) AppendValue(v json.RawMessage) *HubSettingUpdateOne {
	_u.mutation.AppendValue(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *HubSettingUpdateOne) SetRevision(v int64) *HubSettingUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *HubSettingUpdateOne) SetNillableRevision(v *int64) *HubSettingUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *HubSettingUpdateOne) AddRevision(v int64) *HubSettingUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *HubSettingUpdateOne) SetUpdatedBy(v string) *HubSettingUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *HubSettingUpdateOne) SetNillableUpdatedBy(v *string) *HubSettingUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *HubSettingUpdateOne) ClearUpdatedBy() *HubSettingUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *HubSettingUpdateOne) SetUpdateTime(v time.Time) *HubSettingUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the HubSettingMutation object of the builder.
func (_u *HubSettingUpdateOne) Mutation() *HubSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the HubSettingUpdate builder.
func (_u *HubSettingUpdateOne) Where(ps ...predicate.HubSetting) *HubSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HubSettingUpdateOne) Select(field string, fields ...string) *HubSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HubSetting entity.
func (_u *HubSettingUpdateOne) Save(ctx context.Context) (*HubSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubSettingUpdateOne) SaveX(ctx context.Context) *HubSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HubSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := hubsetting.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HubSettingUpdateOne) check() error {
	if v, ok := _u.mutation.Section(); ok {
		if err := hubsetting.SectionValidator(v); err != nil {
			return &ValidationError{Name: "section", err: fmt.Errorf(`ent: validator failed for field "HubSetting.section": %w`, err)}
		}
	}
	return nil
}

func (_u *HubSettingUpdateOne) sqlSave(ctx context.Context) (_node *HubSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hubsetting.Table, hubsetting.Columns, sqlgraph.NewFieldSpec(hubsetting.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HubSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hubsetting.FieldID)
		for _, f := range fields {
			if !hubsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hubsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Section(); ok {
		_spec.SetField(hubsetting.FieldSection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(hubsetting.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hubsetting.FieldValue, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(hubsetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(hubsetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(hubsetting.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(hubsetting.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(hubsetting.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &HubSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
